# Generated by Django 4.0.3 on 2022-04-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_cost',
        ),
    ]
