# Generated by Django 4.0.3 on 2022-04-15 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_remove_cartitem_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='order_by_customer',
            new_name='carted_by_customer',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='ordered_product',
            new_name='carted_product',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
