# Generated by Django 4.0.3 on 2022-04-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_order_by_customer_cartitem_carted_by_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
