# Generated by Django 4.0.3 on 2022-04-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order_flag',
            field=models.IntegerField(default=0),
        ),
    ]
