# Generated by Django 4.0.3 on 2022-04-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cartitem_order_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='order_flag',
            field=models.BooleanField(default=False),
        ),
    ]
